version: "3.1"

services:
  server:
    build:
      context: ./server
    image: "book-repo/server:${TAG:-latest}"
    ports:
      - "5247:80"
    environment:
      - ASPNETCORE_ConnectionStrings__db=Data Source=sql;Initial Catalog=Server;User Id=sa;Password=Th1sI5&Str0ngPa44w0rd;Encrypt=False
      - migrateDB=true
      - Auth0__Domain
      - Auth0__ClientId
      - Auth0__ClientSecret
      - Auth0__Audience
    depends_on:
      - db

  client:
    build:
      context: ./client
    image: "book-repo/client:${TAG:-latest}"
    ports:
      - "3000:80"
    environment:
      - AUTH0_SECRET
      - AUTH0_BASE_URL
      - AUTH0_ISSUER_BASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - BASE_URL

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Th1sI5&Str0ngPa44w0rd
    ports:
      - 1433:1433
