name: Next.js Azure Deployment

on:
  workflow_run:
    workflows: [Next.js Client]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: "Setup npmrc"
        working-directory: ./client
        run: echo -e "\n//npm.pkg.github.com/:_authToken-${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc

      - name: Install dependencies
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Build API client
        working-directory: ./client
        run: npm run build:client

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/client
          registryUrl: ${{ secrets.REGISTRY_URL }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ secrets.CLIENT_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.REGISTRY_URL }}/${{ secrets.CLIENT_CONTAINER_APP_NAME }}:latest
          _buildArgumentsKey_: |
            _buildArgumentsValues_
